"""add_project_statuses_suspended_abandoned

Revision ID: 66ae9febad80
Revises: ad0d6c4ba66b
Create Date: 2026-05-23 22:15:08.164868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ae9febad80'
down_revision: Union[str, Sequence[str], None] = 'ad0d6c4ba66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
