"""add_profile_picture_and_recorded_at

Revision ID: 6ebb7ba765bf
Revises: 0ab6f014cec0
Create Date: 2026-04-10 19:46:17.418776

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ebb7ba765bf"
down_revision: str | Sequence[str] | None = "0ab6f014cec0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contributions", sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("contributions", sa.Column("recorded_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "contributions", "members", ["recorded_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column("members", sa.Column("profile_picture_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "profile_picture_url")
    op.drop_constraint(None, "contributions", type_="foreignkey")
    op.drop_column("contributions", "recorded_by")
    op.drop_column("contributions", "recorded_at")
    # ### end Alembic commands ###
